version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: user_qit
      MONGO_INITDB_ROOT_PASSWORD: 123

    ports:
      - "27017:27017"
    expose:
      - "27017:27017"


  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: user_qit
      ME_CONFIG_MONGODB_ADMINPASSWORD: 123
      ME_CONFIG_MONGODB_URL: mongodb://user_qit:123@mongo:27017/
      ME_CONFIG_BASICAUTH: false
    depends_on:
      - mongo
