version: "3.8"

services:
  postgres:
    container_name: kzh-postgres
    image: postgres
    expose:
      - "5432"
    environment:
      POSTGRES_USER: user_qit
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: kzh
    volumes:
      - ./dataset:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    restart: unless-stopped