spring:
  application:
    name: KzH
  datasource:
    url: jdbc:postgresql://${DATABASE_DOMAIN:localhost}:${DATABASE_PORT:5432}/${DATABASE_NAME:kzh}
    username: ${DATABASE_USERNAME:user_qit}
    password: ${DATABASE_PASSWORD:123}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    defer-datasource-initialization: true
    show-sql: true
  sql:
    init:
      mode: always

server:
  servlet:
    context-path: '/api/'
  error:
    include-message: always
  port: ${PORT:8080}
  address: 0.0.0.0