spring:
  application:
    name: KzH
  data:
    mongodb:
      uri: mongodb://user_qit:123@localhost:27017/admin
      database: kzh
      auto-index-creation: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    defer-datasource-initialization: true
    show-sql: true
  sql:
    init:
      mode: always

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000
      refresh-token:
        expiration: 604800000

server:
  servlet:
    context-path: '/api/'
  error:
    include-message: always
  port: ${PORT:8080}
  address: 0.0.0.0

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: debug