INSERT INTO module (created_at, is_deleted, updated_at, description, hours, image_url, level, number, title)
VALUES
    (EXTRACT(EPOCH FROM NOW()), FALSE, EXTRACT(EPOCH FROM NOW()),
     'В этой главе мы рассмотрим древний Казахстан, начиная с каменного века до Тюрков. Будут затронуты периоды бронзового века, а также история народов саков и сарматов. Помимо этого, мы рассмотрим вклад Казахстана в развитие ремесел, земледелия и животноводства. Особое внимание будет уделено уникальным археологическим находкам и памятникам, которые раскроют многогранность прошлого этого удивительного региона.',
     360, 'Modules/1.jpg', 1, 1, 'Древний век'),
    (EXTRACT(EPOCH FROM NOW()), FALSE, EXTRACT(EPOCH FROM NOW()),
     'В этой главе мы перейдем к тюркскому периоду, когда тюркские племена начали активно поселяться на территории Казахстана. Раскроем роль этих племен в формировании ранних тюркских государств и их влияние на культуру и общество региона. Изучим язык и письменность тюрков, их религию и мифологию, а также важные исторические события, определившие будущее этой земли. Погрузимся в богатую и разнообразную историю древнего Казахстана, которая оставила следы в современном облике этой страны.',
     480, 'Modules/2.jpg', 2, 2, 'Тюркский период'),
    (EXTRACT(EPOCH FROM NOW()), FALSE, EXTRACT(EPOCH FROM NOW()),
     'В важным этапом в истории Казахстана было Монгольское вторжение и его последствия. Монгольское завоевание, возглавляемое Чингисханом, имело глубокое влияние на этот регион, приведя к изменениям в политике, экономике и культуре. Исследуем масштабные события этого периода, его последствия для народов Казахстана и их долгосрочные последствия на историческое развитие страны.',
     550, 'Modules/3.jpg', 3, 3, 'Монгольское вторжение и его последствия'),
    (EXTRACT(EPOCH FROM NOW()), FALSE, EXTRACT(EPOCH FROM NOW()),
     'В этой главе мы рассмотрим Казахское ханство, его политическую структуру, роль ханов и их взаимоотношения с соседними государствами. Изучим важные периоды и события, которые повлияли на становление и укрепление ханства. Будут затронуты ключевые ханы и их вклад в формирование культурного и социального облика Казахстана. Также рассмотрим влияние ханства на экономику, торговлю и связи с другими регионами. В результате получим углубленное представление о значимости Казахского ханства в истории этой земли.',
     600, 'Modules/4.jpg', 1, 4, 'Казахское ханство'),
    (EXTRACT(EPOCH FROM NOW()), FALSE, EXTRACT(EPOCH FROM NOW()),
     'В этой главе мы рассмотрим историю Казахского народа с XVIII по XX век. Изучим период казахских ханств и их участие в геополитических событиях. Обратим внимание на влияние российской империи и его последствия для казахской культуры, обычаев и образа жизни. Также рассмотрим события, связанные с формированием Казахской автономной области и переходом в Казахскую ССР. Исследуем развитие национального самосознания и культурного восстановления Казахского народа в XX веке.',
     720, 'Modules/5.jpg', 5, 5, 'Казахский народ в XVIII-XX'),
    (EXTRACT(EPOCH FROM NOW()), FALSE, EXTRACT(EPOCH FROM NOW()),
     'В этой главе мы рассмотрим историю независимости Казахстана. В конце XX века, после распада Советского Союза в 1991 году, Казахстан объявил о своей независимости. Исследуем процесс формирования суверенного государства, включая создание новой конституции, установление политических институтов и развитие экономики. Рассмотрим роль первого Президента Казахстана, Нурсултана Назарбаева, в формировании национальной идентичности и мирного перехода к независимости. Также обратим внимание на внутренние и внешние вызовы, с которыми столкнулся Казахстан в процессе строительства своего суверенного будущего.',
     660, 'Modules/6.jpeg', 1, 6, 'Независимость');


INSERT INTO topic (created_at, is_deleted, updated_at, number, title, module_id)
VALUES
    (EXTRACT(EPOCH FROM NOW()), FALSE, EXTRACT(EPOCH FROM NOW()), 1, 'Каменный век', 1),
    (EXTRACT(EPOCH FROM NOW()), FALSE, EXTRACT(EPOCH FROM NOW()), 2, 'Бронзовый век', 1),
    (EXTRACT(EPOCH FROM NOW()), FALSE, EXTRACT(EPOCH FROM NOW()), 3, 'Саки', 1),
    (EXTRACT(EPOCH FROM NOW()), FALSE, EXTRACT(EPOCH FROM NOW()), 4, 'Сарматы', 1),
    (EXTRACT(EPOCH FROM NOW()), FALSE, EXTRACT(EPOCH FROM NOW()), 1, 'Тюркский каганат и Согдийцы', 2),
    (EXTRACT(EPOCH FROM NOW()), FALSE, EXTRACT(EPOCH FROM NOW()), 2, 'Западнотюркский и восточнотюркский каганат', 2),
    (EXTRACT(EPOCH FROM NOW()), FALSE, EXTRACT(EPOCH FROM NOW()), 3, 'Тюргеши и карлуки', 2),
    (EXTRACT(EPOCH FROM NOW()), FALSE, EXTRACT(EPOCH FROM NOW()), 4, 'Караханиды и каракитайцы', 2),
    (EXTRACT(EPOCH FROM NOW()), FALSE, EXTRACT(EPOCH FROM NOW()), 5, 'Огузы, Кимаки, Кипчаки', 2),
    (EXTRACT(EPOCH FROM NOW()), FALSE, EXTRACT(EPOCH FROM NOW()), 6, 'ВШП, города и религии', 2),
    (EXTRACT(EPOCH FROM NOW()), FALSE, EXTRACT(EPOCH FROM NOW()), 7, 'Письменность, литература, наука', 2),
    (EXTRACT(EPOCH FROM NOW()), FALSE, EXTRACT(EPOCH FROM NOW()), 1, 'Монгольское вторжение', 3),
    (EXTRACT(EPOCH FROM NOW()), FALSE, EXTRACT(EPOCH FROM NOW()), 2, 'Золотая Орда', 3),
    (EXTRACT(EPOCH FROM NOW()), FALSE, EXTRACT(EPOCH FROM NOW()), 3, 'Ак Орда и Ханство Абулхаира', 3),
    (EXTRACT(EPOCH FROM NOW()), FALSE, EXTRACT(EPOCH FROM NOW()), 4, 'Сибирское ханство и Ногайская Орда', 3),
    (EXTRACT(EPOCH FROM NOW()), FALSE, EXTRACT(EPOCH FROM NOW()), 5, 'Государство Эмира Тимура и Могулистан', 3),
    (EXTRACT(EPOCH FROM NOW()), FALSE, EXTRACT(EPOCH FROM NOW()), 6, 'Экономика и культура послемонгольского периода', 3),
    (EXTRACT(EPOCH FROM NOW()), FALSE, EXTRACT(EPOCH FROM NOW()), 1, 'Формирование Казахского народа', 4),
    (EXTRACT(EPOCH FROM NOW()), FALSE, EXTRACT(EPOCH FROM NOW()), 2, 'Образование Казахского ханства', 4),
    (EXTRACT(EPOCH FROM NOW()), FALSE, EXTRACT(EPOCH FROM NOW()), 3, 'Ханы от Керея до Тауке', 4),
    (EXTRACT(EPOCH FROM NOW()), FALSE, EXTRACT(EPOCH FROM NOW()), 4, 'Казахско-джунгарские войны', 4),
    (EXTRACT(EPOCH FROM NOW()), FALSE, EXTRACT(EPOCH FROM NOW()), 1, 'Присоединение к Российской империи', 5),
    (EXTRACT(EPOCH FROM NOW()), FALSE, EXTRACT(EPOCH FROM NOW()), 2, 'Ханство Абылая. Культура 18 века', 5),
    (EXTRACT(EPOCH FROM NOW()), FALSE, EXTRACT(EPOCH FROM NOW()), 3, 'Восстания Е. Пугачева и С. Датулы', 5),
    (EXTRACT(EPOCH FROM NOW()), FALSE, EXTRACT(EPOCH FROM NOW()), 4, 'Ликвидация ханской власти. Восстания', 5),
    (EXTRACT(EPOCH FROM NOW()), FALSE, EXTRACT(EPOCH FROM NOW()), 5, 'Бокеевская Орда. Восстания в Бокеевской орде', 5),
    (EXTRACT(EPOCH FROM NOW()), FALSE, EXTRACT(EPOCH FROM NOW()), 6, 'Восстание Кенесары Касымова', 5),
    (EXTRACT(EPOCH FROM NOW()), FALSE, EXTRACT(EPOCH FROM NOW()), 7, 'Присоединение старшего жуза к России. Восстания', 5),
    (EXTRACT(EPOCH FROM NOW()), FALSE, EXTRACT(EPOCH FROM NOW()), 8, 'Реформы 1867-1868 годов. Восстания', 5),
    (EXTRACT(EPOCH FROM NOW()), FALSE, EXTRACT(EPOCH FROM NOW()), 9, 'Реформы 1880-1890-х годов. Экономика в 19 веке', 5),
    (EXTRACT(EPOCH FROM NOW()), FALSE, EXTRACT(EPOCH FROM NOW()), 10, 'Национальная обстановка в 19 веке', 5),
    (EXTRACT(EPOCH FROM NOW()), FALSE, EXTRACT(EPOCH FROM NOW()), 11, 'Культура и наука 19 века', 5),
    (EXTRACT(EPOCH FROM NOW()), FALSE, EXTRACT(EPOCH FROM NOW()), 12, 'Культура второй половины 19 и начала 20 веков', 5),
    (EXTRACT(EPOCH FROM NOW()), FALSE, EXTRACT(EPOCH FROM NOW()), 13, 'Казахстан в начале 20 века', 5),
    (EXTRACT(EPOCH FROM NOW()), FALSE, EXTRACT(EPOCH FROM NOW()), 14, 'Восстание 1916 года', 5),
    (EXTRACT(EPOCH FROM NOW()), FALSE, EXTRACT(EPOCH FROM NOW()), 15, 'Революции 1917 года', 5),
    (EXTRACT(EPOCH FROM NOW()), FALSE, EXTRACT(EPOCH FROM NOW()), 16, 'Автономии в Казахстане', 5),
    (EXTRACT(EPOCH FROM NOW()), FALSE, EXTRACT(EPOCH FROM NOW()), 17, 'Установление советской власти. Гражданская война', 5),
    (EXTRACT(EPOCH FROM NOW()), FALSE, EXTRACT(EPOCH FROM NOW()), 18, 'Образование КазАССР', 5),
    (EXTRACT(EPOCH FROM NOW()), FALSE, EXTRACT(EPOCH FROM NOW()), 19, 'НЭП и индустриализация', 5),
    (EXTRACT(EPOCH FROM NOW()), FALSE, EXTRACT(EPOCH FROM NOW()), 20, 'Коллективизация', 5),
    (EXTRACT(EPOCH FROM NOW()), FALSE, EXTRACT(EPOCH FROM NOW()), 21, 'Казахстан в предвоенные годы', 5),
    (EXTRACT(EPOCH FROM NOW()), FALSE, EXTRACT(EPOCH FROM NOW()), 22, 'Казахстан в годы ВОВ', 5),
    (EXTRACT(EPOCH FROM NOW()), FALSE, EXTRACT(EPOCH FROM NOW()), 23, 'Казахстан в послевоенные годы', 5),
    (EXTRACT(EPOCH FROM NOW()), FALSE, EXTRACT(EPOCH FROM NOW()), 24, 'Период Застоя', 5),
    (EXTRACT(EPOCH FROM NOW()), FALSE, EXTRACT(EPOCH FROM NOW()), 25, 'Перестройка', 5),
    (EXTRACT(EPOCH FROM NOW()), FALSE, EXTRACT(EPOCH FROM NOW()), 1, 'Независимый Казахстан', 6);
